import { Chain, UpdateRule } from '../../simulationRunConfigModels';

export const DifferenceMomentumState: UpdateRule = {
  updateRuleName: 'Difference Momentum',
  updateRuleKey: 'difference_momentum',
  updateRuleSimKey: 'difference_momentum',
  updateRuleRunUrl: 'runSimulation',
  updateRuleTrainUrl: 'runTraining',
  applicablePoolTypes: ['QuantAMM'],
  chainDeploymentDetails: new Map<Chain, string>(),
  updateRuleResultProfileSummary:
    'This rule implements a Moving Average Convergence Divergence strategy. It uses two moving averages, one short and one long, and compares their difference to determine a change in pool weights.',
  heatmapKeys: [],
  updateRuleParameters: [
    {
      factorName: 'k_per_day',
      factorDisplayName: 'K per day',
      factorDescription: 'Determines how aggressive the pool is',
      applicableCoins: [],
      factorValue: '12',
      minValue: '-100',
      maxValue: '5000',
      smartContractSortOrder: 0,
    },
    {
      factorName: 'memory_days_2',
      factorDisplayName: 'Short memory in days',
      factorDescription: 'The memory of the short moving average',
      applicableCoins: [],
      factorValue: '10',
      minValue: '1',
      maxValue: '1095',
      smartContractSortOrder: 2,
    },
    {
      factorName: 'memory_days_1',
      factorDisplayName: 'Long memory in days',
      factorDescription: 'The memory of the long moving average',
      applicableCoins: [],
      factorValue: '30',
      minValue: '1',
      maxValue: '1095',
      smartContractSortOrder: 3,
    },
  ],
};

export const LvrDifferenceMomentumState: UpdateRule = {
  updateRuleName: 'LVR - Difference Momentum',
  updateRuleKey: 'lvr__difference_momentum',
  updateRuleSimKey: 'lvr__difference_momentum',
  updateRuleRunUrl: 'runSimulation',
  updateRuleTrainUrl: 'runTraining',
  applicablePoolTypes: ['LVR for QuantAMM'],
  chainDeploymentDetails: new Map<Chain, string>(),
  updateRuleResultProfileSummary:
    'This rule implements a Moving Average Convergence Divergence strategy. It uses two moving averages, one short and one long, and compares their difference to determine a change in pool weights.',
  heatmapKeys: [],
  updateRuleParameters: [
    {
      factorName: 'k_per_day',
      factorDisplayName: 'K per day',
      factorDescription: 'Determines how aggressive the pool is',
      applicableCoins: [],
      factorValue: '12',
      minValue: '-100',
      maxValue: '5000',
      smartContractSortOrder: 1,
    },
    {
      factorName: 'memory_days_2',
      factorDisplayName: 'Short memory in days',
      factorDescription: 'The memory of the short moving average',
      applicableCoins: [],
      factorValue: '10',
      minValue: '1',
      maxValue: '1095',
      smartContractSortOrder: 2,
    },
    {
      factorName: 'memory_days_1',
      factorDisplayName: 'Long memory in days',
      factorDescription: 'The memory of the long moving average',
      applicableCoins: [],
      factorValue: '30',
      minValue: '1',
      maxValue: '1095',
      smartContractSortOrder: 3,
    },
  ],
};

export const RvrDifferenceMomentumState: UpdateRule = {
  updateRuleName: 'RVR - Difference Momentum',
  updateRuleKey: 'rvr__difference_momentum',
  updateRuleSimKey: 'rvr__difference_momentum',
  updateRuleRunUrl: 'runSimulation',
  updateRuleTrainUrl: 'runTraining',
  applicablePoolTypes: ['RVR for QuantAMM'],
  chainDeploymentDetails: new Map<Chain, string>(),
  updateRuleResultProfileSummary:
    'This rule implements a Moving Average Convergence Divergence strategy. It uses two moving averages, one short and one long, and compares their difference to determine a change in pool weights.',
  heatmapKeys: [],
  updateRuleParameters: [
    {
      factorName: 'k_per_day',
      factorDisplayName: 'K per day',
      factorDescription: 'Determines how aggressive the pool is',
      applicableCoins: [],
      factorValue: '12',
      minValue: '-100',
      maxValue: '5000',
      smartContractSortOrder: 1,
    },
    {
      factorName: 'memory_days_2',
      factorDisplayName: 'Short memory in days',
      factorDescription: 'The memory of the short moving average',
      applicableCoins: [],
      factorValue: '10',
      minValue: '1',
      maxValue: '1095',
      smartContractSortOrder: 2,
    },
    {
      factorName: 'memory_days_1',
      factorDisplayName: 'Long memory in days',
      factorDescription: 'The memory of the long moving average',
      applicableCoins: [],
      factorValue: '30',
      minValue: '1',
      maxValue: '1095',
      smartContractSortOrder: 3,
    },
  ],
};
