import { Chain, UpdateRule } from '../../simulationRunConfigModels';

export const TruflationBtcRegimeState: UpdateRule = {
  updateRuleName: 'Truflation BTC Regime',
  updateRuleKey: 'truflation_regime',
  updateRuleSimKey: 'regime_detection',
  updateRuleRunUrl: 'runSimulation',
  updateRuleTrainUrl: 'runTraining',
  applicablePoolTypes: ['QuantAMM'],
  chainDeploymentDetails: new Map<Chain, string>(),
  updateRuleResultProfileSummary:
    'TODO MW explanation of truflation regime strat?',
  heatmapKeys: [],
  updateRuleParameters: [
    {
      factorName: 'slope_length',
      factorDisplayName: 'Slope Length',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '15.0',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 4,
    },
    {
      factorName: 'threshold_up',
      factorDisplayName: 'Threshold Up',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '0.0125',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 0,
    },
    {
      factorName: 'threshold_down',
      factorDisplayName: 'Threshold Down',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '-0.0125',
      minValue: '-5000',
      maxValue: '0',
      smartContractSortOrder: 0,
    },
    {
      factorName: 'flat_buffer_up',
      factorDisplayName: 'Flat Buffer Up',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '0.005',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 1,
    },
    {
      factorName: 'flat_buffer_down',
      factorDisplayName: 'Flat Buffer Down',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '-0.005',
      minValue: '-5000',
      maxValue: '0',
      smartContractSortOrder: 1,
    },
    {
      factorName: 'confirm_up_days',
      factorDisplayName: 'Confirm Up Days',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '5',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 2,
    },
    {
      factorName: 'confirm_down_days',
      factorDisplayName: 'Confirm Down Days',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '5',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 2,
    },
    {
      factorName: 'confirm_flat_days',
      factorDisplayName: 'Confirm Flat Days',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '4',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 3,
    },
  ],
};

export const LvrTruflationBtcRegimeState: UpdateRule = {
  updateRuleName: 'Truflation BTC Regime',
  updateRuleKey: 'truflation_regime',
  updateRuleSimKey: 'regime_detection',
  updateRuleRunUrl: 'runSimulation',
  updateRuleTrainUrl: 'runTraining',
  applicablePoolTypes: ['QuantAMM'],
  chainDeploymentDetails: new Map<Chain, string>(),
  updateRuleResultProfileSummary:
    'TODO MW explanation of truflation regime strat?',
  heatmapKeys: [],
  updateRuleParameters: [
    {
      factorName: 'slope_length',
      factorDisplayName: 'Slope Length',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '15.0',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 4,
    },
    {
      factorName: 'threshold_up',
      factorDisplayName: 'Threshold Up',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '0.0125',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 0,
    },
    {
      factorName: 'threshold_down',
      factorDisplayName: 'Threshold Down',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '-0.0125',
      minValue: '-5000',
      maxValue: '0',
      smartContractSortOrder: 0,
    },
    {
      factorName: 'flat_buffer_up',
      factorDisplayName: 'Flat Buffer Up',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '0.005',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 1,
    },
    {
      factorName: 'flat_buffer_down',
      factorDisplayName: 'Flat Buffer Down',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '-0.005',
      minValue: '-5000',
      maxValue: '0',
      smartContractSortOrder: 1,
    },
    {
      factorName: 'confirm_up_days',
      factorDisplayName: 'Confirm Up Days',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '5',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 2,
    },
    {
      factorName: 'confirm_down_days',
      factorDisplayName: 'Confirm Down Days',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '5',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 2,
    },
    {
      factorName: 'confirm_flat_days',
      factorDisplayName: 'Confirm Flat Days',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '4',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 3,
    },
  ],
};

export const RvrTruflationBtcRegimeState: UpdateRule = {
  updateRuleName: 'Truflation BTC Regime',
  updateRuleKey: 'truflation_regime',
  updateRuleSimKey: 'regime_detection',
  updateRuleRunUrl: 'runSimulation',
  updateRuleTrainUrl: 'runTraining',
  applicablePoolTypes: ['QuantAMM'],
  chainDeploymentDetails: new Map<Chain, string>(),
  updateRuleResultProfileSummary:
    'TODO MW explanation of truflation regime strat?',
  heatmapKeys: [],
  updateRuleParameters: [
    {
      factorName: 'slope_length',
      factorDisplayName: 'Slope Length',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '15.0',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 4,
    },
    {
      factorName: 'threshold_up',
      factorDisplayName: 'Threshold Up',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '0.0125',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 0,
    },
    {
      factorName: 'threshold_down',
      factorDisplayName: 'Threshold Down',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '-0.0125',
      minValue: '-5000',
      maxValue: '0',
      smartContractSortOrder: 0,
    },
    {
      factorName: 'flat_buffer_up',
      factorDisplayName: 'Flat Buffer Up',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '0.005',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 1,
    },
    {
      factorName: 'flat_buffer_down',
      factorDisplayName: 'Flat Buffer Down',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '-0.005',
      minValue: '-5000',
      maxValue: '0',
      smartContractSortOrder: 1,
    },
    {
      factorName: 'confirm_up_days',
      factorDisplayName: 'Confirm Up Days',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '5',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 2,
    },
    {
      factorName: 'confirm_down_days',
      factorDisplayName: 'Confirm Down Days',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '5',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 2,
    },
    {
      factorName: 'confirm_flat_days',
      factorDisplayName: 'Confirm Flat Days',
      factorDescription: 'TODO MW',
      applicableCoins: [],
      factorValue: '4',
      minValue: '0',
      maxValue: '5000',
      smartContractSortOrder: 3,
    },
  ],
};
