import type { FinancialMetricThresholds } from './productModels';

export const CURRENT_PERFORMANCE_PERIOD = '3m';

export const INITIAL_LOAD_POOLS_COUNT = 20;

export const INITIAL_PAGE = 1;

export const returnMetricThresholds: FinancialMetricThresholds[] = [
  {
    key: 'Absolute Return (%)',
    veryLow: 0,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 2,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 10,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription: 'Absolute return over the selected period.',
  },
  {
    key: 'Annualized Calmar Ratio',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 2,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 3,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Calmar ratio is a risk-adjusted return metric. It is calculated as the annualized return divided by the maximum drawdown over the selected period. Higher values indicate better risk-adjusted performance.',
  },
  {
    key: 'Annualized Omega Ratio',
    veryLow: 1,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1.5,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 2.5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 3,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Omega ratio is a risk-adjusted return metric comparing the probability-weighted gains to probability-weighted losses relative to a chosen threshold over the selected period. Higher values indicate better risk-adjusted performance.',
  },
  {
    key: 'Annualized Return on VaR',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 2,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 3,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Return on VaR is a risk-adjusted return metric calculated as the annualized return divided by Value at Risk (VaR) over the selected period. Higher values indicate better return per unit of VaR.',
  },
  {
    key: 'Annualized Sharpe Ratio',
    veryLow: 0.3,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 0.6,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 1.5,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Sharpe ratio is a risk-adjusted return metric. It is calculated as the annualized excess return divided by the annualized volatility over the selected period. Higher values indicate better risk-adjusted performance.',
  },
  {
    key: 'Annualized Sortino Ratio',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1.5,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 2.5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 3.5,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Sortino ratio is a downside-risk-adjusted return metric. It is calculated as the annualized excess return divided by downside deviation over the selected period. Higher values indicate better downside-risk-adjusted performance.',
  },
  {
    key: 'Conditional Drawdown at Risk',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1.5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 2,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Conditional Drawdown at Risk (CDaR) measures tail drawdown risk as the expected drawdown beyond a specified confidence level over the selected period. Lower values indicate lower tail drawdown risk.',
  },
  {
    key: 'Daily Returns Maximum Drawdown',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1.5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 2,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Maximum drawdown (daily returns) is the largest peak-to-trough decline observed over the selected period. Lower values (closer to 0) indicate less severe drawdowns.',
  },
  {
    key: 'Monthly Returns Maximum Drawdown',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1.5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 2,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Maximum drawdown (monthly returns) is the largest peak-to-trough decline observed over the selected period. Lower values (closer to 0) indicate less severe drawdowns.',
  },
  {
    key: 'Return on VaR',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1.5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 2,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Return on VaR is a risk-adjusted return metric calculated as the return divided by Value at Risk (VaR) over the selected period. Higher values indicate better return per unit of VaR.',
  },
  {
    key: 'Sharpe Ratio',
    veryLow: 0.4,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 0.8,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1.2,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 1.6,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Sharpe ratio is a risk-adjusted return metric. It is calculated as the excess return divided by volatility over the selected period. Higher values indicate better risk-adjusted performance.',
  },
  {
    key: 'Sterling Ratio',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1.5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 2,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Sterling ratio is a drawdown-adjusted return metric, commonly calculated as annualized return divided by an average (or expected) drawdown measure over the selected period. Higher values indicate better drawdown-adjusted performance.',
  },
  {
    key: 'Ulcer Index',
    veryLow: 10,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 5,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 2,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 1,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Ulcer Index is a drawdown-based risk metric (based on the depth and duration of drawdowns) over the selected period. Lower values indicate smaller and shorter drawdowns.',
  },
  {
    key: 'Weekly Returns Maximum Drawdown',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1.5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 2,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Maximum drawdown (weekly returns) is the largest peak-to-trough decline observed over the selected period. Lower values (closer to 0) indicate less severe drawdowns.',
  },
  {
    key: 'Kurtosis',
    veryLow: 7,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 4,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 2,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 1,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Kurtosis measures the tailedness of the return distribution over the selected period. Higher kurtosis indicates a greater likelihood of extreme outcomes; lower values generally indicate lower tail risk.',
  },
  {
    key: 'Skewness',
    veryLow: -1,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 0,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 2,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Skewness measures the asymmetry of the return distribution over the selected period. Positive skewness indicates a right-skewed distribution (more upside tail), while negative skewness indicates a left-skewed distribution (more downside tail).',
  },
  {
    key: 'Volatility (Std Dev)',
    veryLow: 25,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 15,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 7,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 5,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Standard deviation of returns is a measure of volatility over the selected period. Higher standard deviation indicates higher volatility (risk).',
  },
];

export const benchmarkMetricThresholds: FinancialMetricThresholds[] = [
  {
    key: 'Annualized Information Ratio',
    veryLow: 0,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 0.5,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 2,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Information ratio is a risk-adjusted excess return metric. It is calculated as the annualized excess return over the benchmark divided by tracking error over the selected period. Higher values indicate better risk-adjusted outperformance.',
  },
  {
    key: "Annualized Jensen's Alpha",
    veryLow: 0,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 0.005,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 0.02,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 0.04,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Jensen’s Alpha measures risk-adjusted excess return relative to the benchmark based on CAPM over the selected period. Higher values indicate better risk-adjusted outperformance.',
  },
  {
    key: "Annualized Jensen's Alpha (%)",
    veryLow: 0,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 0.5,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 2,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 4,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Jensen’s Alpha (%) measures risk-adjusted excess return relative to the benchmark based on CAPM over the selected period. Higher values indicate better risk-adjusted outperformance.',
  },
  {
    key: 'Beta',
    veryLow: 0.75,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 0.25,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 0.1,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 0.05,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Beta measures sensitivity to benchmark movements over the selected period. Lower beta indicates lower market sensitivity (more defensive or market-neutral behavior).',
  },
  {
    key: 'Daily VaR (95)',
    veryLow: 3,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 2,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 0.5,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Value at Risk (VaR) estimates the potential loss over a given horizon at a chosen confidence level during the selected period. Lower VaR indicates lower downside risk.',
  },
  {
    key: 'Downside Capture Ratio',
    veryLow: 110,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 90,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 75,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 60,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Downside Capture Ratio measures performance relative to the benchmark during periods when the benchmark is negative over the selected period. Lower values indicate capturing less of the benchmark’s downside.',
  },
  {
    key: 'Total Capture Ratio',
    veryLow: 0.75,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1.25,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 1.5,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Total Capture Ratio measures performance relative to the benchmark across all periods within the selected period. Values above 1 indicate the product captured more of the benchmark’s returns overall; values below 1 indicate less.',
  },
  {
    key: 'Tracking Error',
    veryLow: 8,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 4,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 0.5,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Tracking Error is the volatility of the product’s excess return versus the benchmark over the selected period. Lower values indicate lower active risk.',
  },
  {
    key: 'Upside Capture Ratio',
    veryLow: 90,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 100,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 110,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 120,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Upside Capture Ratio measures performance relative to the benchmark during periods when the benchmark is positive over the selected period. Higher values indicate capturing more of the benchmark’s upside.',
  },
  {
    key: 'Volatility',
    veryLow: 25,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 15,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 7,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 5,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Volatility measures the dispersion of returns around the mean over the selected period. Lower volatility indicates lower risk.',
  },
];
