export const CURRENT_PERFORMANCE_PERIOD = '3m';

export const INITIAL_LOAD_POOLS_COUNT = 20;

export const INITIAL_PAGE = 1;

export const returnMetricThresholds = [
  {
    key: 'Annualized Calmer Ratio',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 2,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 3,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Calmar ratio is a risk-adjusted measure of return. It is calculated as the ratio of the annualized return over the maximum drawdown over the past 36 months. The higher the Calmar ratio, the better the risk-adjusted return.',
  },
  {
    key: 'Annualized Omega Ratio',
    veryLow: 1,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1.5,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 2.5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 3,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Omega ratio is a risk-adjusted measure of return. It is calculated as the ratio of the probability-weighted return over a target return. The higher the Omega ratio, the better the risk-adjusted return.',
  },
  {
    key: 'Annualized Return on VaR',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 2,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 3,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Return on VaR is a risk-adjusted measure of return. It is calculated as the ratio of the annualized return over the annualized Value at Risk (VaR) over the past 36 months. The higher the Return on VaR, the better the risk-adjusted return.',
  },
  {
    key: 'Annualized Sharpe Ratio',
    veryLow: 0.3,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 0.6,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 1.5,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Sharpe ratio is a risk-adjusted measure of return. It is calculated as the ratio of the annualized return over the annualized standard deviation of returns over the past 36 months. The higher the Sharpe ratio, the better the risk-adjusted return.',
  },
  {
    key: 'Annualized Sortino Ratio',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1.5,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 2.5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 3.5,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Sortino ratio is a risk-adjusted measure of return. It is calculated as the ratio of the annualized return over the downside deviation of returns over the past 36 months. The higher the Sortino ratio, the better the risk-adjusted return.',
  },
  {
    key: 'Conditional Drawdown at Risk',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1.5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 2,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Conditional Drawdown at Risk is a risk-adjusted measure of return. It is calculated as the ratio of the annualized return over the conditional Value at Risk (VaR) over the past 36 months. The higher the Conditional Drawdown at Risk, the better the risk-adjusted return.',
  },
  {
    key: 'Daily Returns Maximum Drawdown',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1.5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 2,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Maximum Drawdown is a risk-adjusted measure of return. It is calculated as the ratio of the annualized return over the maximum drawdown over the past 36 months. The higher the Maximum Drawdown, the better the risk-adjusted return.',
  },
  {
    key: 'Monthly Returns Maximum Drawdown',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1.5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 2,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Maximum Drawdown is a risk-adjusted measure of return. It is calculated as the ratio of the annualized return over the maximum drawdown over the past 36 months. The higher the Maximum Drawdown, the better the risk-adjusted return.',
  },
  {
    key: 'Return on VaR',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1.5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 2,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Return on VaR is a risk-adjusted measure of return. It is calculated as the ratio of the annualized return over the annualized Value at Risk (VaR) over the past 36 months. The higher the Return on VaR, the better the risk-adjusted return.',
  },
  {
    key: 'Sharpe Ratio',
    veryLow: 0.4,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 0.8,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1.2,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 1.6,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Sharpe ratio is a risk-adjusted measure of return. It is calculated as the ratio of the annualized return over the annualized standard deviation of returns over the past 36 months. The higher the Sharpe ratio, the better the risk-adjusted return.',
  },
  {
    key: 'Sterling Ratio',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1.5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 2,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Sterling ratio is a risk-adjusted measure of return. It is calculated as the ratio of the annualized return over the downside deviation of returns over the past 36 months. The higher the Sterling ratio, the better the risk-adjusted return.',
  },
  {
    key: 'Ulcer Index',
    veryLow: 10,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 5,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 2,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 1,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Ulcer Index is a risk-adjusted measure of return. It is calculated as the ratio of the annualized return over the maximum drawdown over the past 36 months. The higher the Ulcer Index, the better the risk-adjusted return.',
  },
  {
    key: 'Weekly Returns Maximum Drawdown',
    veryLow: 0.5,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1.5,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 2,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Maximum Drawdown is a risk-adjusted measure of return. It is calculated as the ratio of the annualized return over the maximum drawdown over the past 36 months. The higher the Maximum Drawdown, the better the risk-adjusted return.',
  },
  {
    key: 'kurtosis',
    veryLow: 7,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 4,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 2,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 1,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Kurtosis is a measure of the "tailedness" of the probability distribution of returns. A high kurtosis indicates a high probability of extreme values in the distribution.',
  },
  {
    key: 'skewness',
    veryLow: -1,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 0,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 2,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Skewness is a measure of the asymmetry of the probability distribution of returns. A positive skewness indicates a right-skewed distribution, while a negative skewness indicates a left-skewed distribution.',
  },
  {
    key: 'std',
    veryLow: 25,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 15,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 7,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 5,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The standard deviation of returns is a measure of the dispersion of returns around the mean return. A higher standard deviation indicates higher volatility.',
  },
];

export const benchmarkMetricThresholds = [
  {
    key: 'Annualized Information Ratio',
    veryLow: 0,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 0.5,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 2,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Information ratio is a risk-adjusted measure of return. It is calculated as the ratio of the annualized excess return over the benchmark over the annualized tracking error over the past 36 months. The higher the Information ratio, the better the risk-adjusted return.',
  },
  {
    key: "Annualized Jensen's Alpha",
    veryLow: 0,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 0.005,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 0.02,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 0.04,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Jensen’s Alpha is a risk-adjusted measure of return. It is calculated as the excess return over the benchmark over the expected return based on the Capital Asset Pricing Model (CAPM). The higher the Jensen’s Alpha, the better the risk-adjusted return.',
  },
  {
    key: 'Beta',
    veryLow: 0.75,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 0.25,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 0.1,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 0.05,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Beta is a measure of the sensitivity of the product to market movements. A beta of 1 indicates that the product moves in line with the market, while a beta greater than 1 indicates that the product is more volatile than the market.',
  },
  {
    key: 'Daily VaR (95)',
    veryLow: 3,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 2,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 0.5,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Value at Risk (VaR) is a measure of the potential loss in value of a product over a given time period and confidence level. A higher VaR indicates a higher potential loss.',
  },
  {
    key: 'Downside Capture Ratio',
    veryLow: 110,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 90,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 75,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 60,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Downside Capture Ratio is a measure of the product’s performance relative to the benchmark during periods of negative benchmark returns. A downside capture ratio of less than 1 indicates that the product has outperformed the benchmark during periods of negative benchmark returns.',
  },
  {
    key: 'Total Capture Ratio',
    veryLow: 0.75,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 1,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1.25,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 1.5,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Total Capture Ratio is a measure of the product’s performance relative to the benchmark during all periods. A total capture ratio of less than 1 indicates that the product has outperformed the benchmark during all periods.',
  },
  {
    key: 'Tracking Error',
    veryLow: 8,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 4,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 1,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 0.5,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Tracking Error is a measure of the volatility of the excess return of the product over the benchmark. A higher tracking error indicates higher active risk.',
  },
  {
    key: 'Upside Capture Ratio',
    veryLow: 90,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 100,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 110,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 120,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'The Upside Capture Ratio is a measure of the product’s performance relative to the benchmark during periods of positive benchmark returns. An upside capture ratio of more than 1 indicates that the product has outperformed the benchmark during periods of positive benchmark returns.',
  },
  {
    key: 'Volatility',
    veryLow: 25,
    veryLowColor: 'rgba(166, 0, 0, 0.6)',
    low: 15,
    lowColor: 'rgba(220, 109, 6, 0.6)',
    medium: 7,
    mediumColor: 'rgba(240, 228, 6, 0.6)',
    high: 5,
    highColor: 'rgba(2, 189, 46, 0.6)',
    tooltipDescription:
      'Volatility is a measure of the dispersion of returns around the mean return. A higher volatility indicates higher risk.',
  },
];