export enum ROUTES {
  HOME = 'home',
  DOCUMENTATION = 'documentation',
  PRODUCT_EXPLORER = 'product-explorer',
  COINS = 'coins',
  SIMULATION_RUNNER = 'simulation-runner',
  SIMULATION_COMPARER = 'simulation-results-comparer',
  EXAMPLES = 'examples',
  RESEARCH = 'research',
  COMPANY = 'company',
  CONTACT = 'contact',
  TOS = 'tos',
  SAFEHAVENFACTSHEET = '0x6b61d8680c4f9e560c8306807908553f95c749c5',
  INELIGIBLEUSER = 'ineligible-user',
}
